NensquefemCoreBundle:
    resource: "@NensquefemCoreBundle/Controller/"
    type:     annotation
    prefix:   /

#JordiLlonchEventsManagerBundle:
#    resource: "@JordiLlonchEventsManagerBundle/Controller/"
#    type:     annotation
#    prefix:   /

NensQueFemParsersBundle:
    resource: "@NensQueFemParsersBundle/Controller/"
    type:     annotation
    prefix:   /

#NensQueFemFrontBundle:
#    resource: "@NensQueFemFrontBundle/Controller/"
#    type:     annotation
#    prefix:   /

NensQueFemFrontBundle:
    resource: "@NensQueFemFrontBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
